VocationManagerTest.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VocationManagerTest.Database;
using VocationManagerTest.Database.Model;
using VocationManagerTest.Domain.Interfaces;
using VocationManagerTest.Domain.Model;
using VocationManagerTest.Domain.Model.Employee;
using VocationManagerTest.Domain.Services;
using VocationManagerTest.Shared;
using VocationManagerTest.Web.ViewModels;
using ControllerBase = VocationManagerTest.Web.Controllers.Base.ControllerBase;

namespace VocationManagerTest.Web.Controllers
{
    [Authorize]
    public class EmployeeController : ControllerBase
    {
        private EmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;

        public EmployeeController(EmployeeService employeeService, IDepartmentService departmentService)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
        }

        public async Task<ActionResult> Index(EmployeeListParameters parameters)
        {
            var model = new EmployeeListViewModel
            {
                Parameters = parameters,
                EmployeeList = await _employeeService.GetList(parameters, UserId),
                AvailableDepartments = await _departmentService.GetNames(UserId)
            };
            

            return View("EmployeeList", model);
        }

        public async Task<ActionResult> Remove(int id)
        {
            await _employeeService.Remove(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<ActionResult> Create(int? departmentId)
        {
            var employee = new EditEmployeeDetails();

            if (departmentId.HasValue)
            {
                employee.DepartmentIds = new List<int> { departmentId.Value };
            }

            return await EditView(employee);

        }

        [HttpPost]
        public async Task<ActionResult> Create(EditEmployeeDetails employee)
        {
            return await Save(employee);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var editEmployeeDetails = await _employeeService.GetEditDetails(id);
            if (editEmployeeDetails == null)
            {
                return RedirectToAction("Index");
            }

            return await EditView(editEmployeeDetails);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditEmployeeDetails employee)
        {
            return await Save(employee);
        }


        public async Task<ActionResult> Save(EditEmployeeDetails employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _employeeService.Save(employee);
                    return RedirectToAction("Index");
                }
                catch(Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }
            }
            return await EditView(employee);
        }

        private async Task<ActionResult> EditView(EditEmployeeDetails employee)
        {
            var model = new EditEmployeeViewModel
            {
                Employee = employee,
                AvailableDepartments = await _departmentService.GetNames(UserId)
            };

            return View("EditEmployee", model);
        }

     }
}

VocationManagerTest.Web/Controllers/VacationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VocationManagerTest.Database.Enums;
using VocationManagerTest.Domain.Interfaces;
using VocationManagerTest.Domain.Model.Vacation;
using VocationManagerTest.Shared.Extensions;
using VocationManagerTest.Web.ViewModels;
using ControllerBase = VocationManagerTest.Web.Controllers.Base.ControllerBase;

namespace VocationManagerTest.Web.Controllers
{
    [Authorize]
    public class VacationController : ControllerBase
    {
        private readonly IVacationService _vacationService;
        private readonly IDepartmentService _departmentService;

        public VacationController(IVacationService vacationService, IDepartmentService departmentService)
        {
            _vacationService = vacationService;
            _departmentService = departmentService;
        }

        [Authorize(Roles = "Admin, Head")]
        public async Task<IActionResult> Index(VacationListParameters parameters)
        {
            if (!parameters.DepartmentIds.HasItems() && User.IsInRole(EmployeeRole.Head.ToString()))
            {
                parameters.DepartmentIds = (await _departmentService.GetNames(UserId)).Select(d => d.Id).ToList();
            }

            var model = new VacationListViewModel
            {
                Parameters = parameters,
                VacationList = await _vacationService.GetList(parameters, UserId),
                AvailableYear =  await _vacationService.GetYears(),
                AvailableDepartments = await _departmentService.GetNames(UserId),
            };

            return View("VacationList", model);
        }

        public async Task<ActionResult> ShowVacation(int? id)
        {
            var userId = 0;
            if (User.IsInRole(EmployeeRole.User.ToString()) || (!User.IsInRole(EmployeeRole.User.ToString()) && !id.HasValue))
            {
                userId = UserId;
            }
            else
            {
                if(id.HasValue)
                userId = id.Value;
            }
            var model = await _vacationService.GetDetailsList(userId);
            return View("VacationDetailsList", model);
        }

        [HttpGet]
        public async Task<ActionResult> Create(int? id)
        {
            var userId = 0;
            if (User.IsInRole(EmployeeRole.User.ToString())||(!User.IsInRole(EmployeeRole.User.ToString())&&!id.HasValue))
            {
                userId = UserId;
            }
            else
            {
                if (id.HasValue)
                    userId = id.Value;
            }
            var model = new EditVacationDetails(){EmployeeId = userId};
            return await EditView(model);

        }
        
        [HttpPost]
        public async Task<ActionResult> Create(EditVacationDetails vacation)
        {
            return await Save(vacation);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var editVacationDetails = await _vacationService.GetEditDetails(id);
            if (editVacationDetails == null)
            {
                return RedirectToAction("Index");
            }

            return await EditView(editVacationDetails);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditVacationDetails vacation)
        {
            return await Save(vacation);
        }

        public async Task<ActionResult> Remove(int id)
        {
            await _vacationService.Remove(id);
            return RedirectToAction("ShowVacation");
        }


        public async Task<ActionResult> Save(EditVacationDetails vacation)
        {
            if (ModelState.IsValid && vacation.BeginningDate >= DateTime.Now &&
                                          vacation.BeginningDate <= vacation.ExpirationDate)
            {
                try
                {
                    await _vacationService.Save(vacation);
                    return RedirectToAction("ShowVacation");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }
            }
            else
            {
                return RedirectToAction("Create");
            }
            return await EditView(vacation);
        }

        private async Task<ActionResult> EditView(EditVacationDetails vacation)
        {

            var model = new EditVacationViewModel
            {
                Vacation = vacation
            };

            return View("EditVacation", model);
        }




    }
}

VocationManagerTest.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using VocationManagerTest.Database.Enums
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VocationManagerTest.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VocationManagerTest.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (!User.IsInRole(EmployeeRole.User.ToString()))
                         {
                             <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Vacation" asp-action="Index">Отпуска сотрудников</a>
                             </li>
                         }

                        @if (User.IsInRole(EmployeeRole.Admin.ToString()))
                         {
                             <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Отделы</a>
                             </li>
                         }
                        @if (!User.IsInRole(EmployeeRole.User.ToString()))
                         {
                             <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Пользователи</a>
                             </li>
                         }
                    }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="null" asp-controller="Vacation" asp-action="ShowVacation">Мои отпуска</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark float-right" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - VocationManagerTest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>